version: 2

models:
  - name: fct_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
