version: 2

models:
  - name: fct_orders
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
      - name: amount
        description: rounded dollar amount of order
        data_tests:
          # - greater_than_five
          # - dbt_utils.expression_is_true:
          #     arguments:
          #       expression: "<= 5"
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: 0  # (Optional)
                max_value: 100 # (Optional)
                # row_condition: "id is not null" # (Optional)
                strictly: false # (Optional. Default is 'false'. Adds an 'or equal to' to the comparison operator for min/max)
          - assert_dollars_spent_greater_than_one:
              arguments:
                group_by_column: customer_id